version: "3"

services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./build/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./src:/src
    restart: always
    expose:
      - "80"
